import { PDFDocument, StandardFonts, rgb } from "pdf-lib";

export async function buildInvoicePdfBytes(input: {
  invoiceNo: string;
  amount: string;
  currency: string;
  status: string;
  issueDate: string;
  subscriberUsername: string;
}): Promise<Uint8Array> {
  const doc = await PDFDocument.create();
  const page = doc.addPage([612, 792]);
  const font = await doc.embedFont(StandardFonts.Helvetica);
  let y = 750;
  const draw = (text: string, size = 11) => {
    page.drawText(text, { x: 50, y, size, font, color: rgb(0.1, 0.1, 0.12) });
    y -= size + 6;
  };
  draw("Future Radius — Invoice", 16);
  draw(`Invoice: ${input.invoiceNo}`);
  draw(`Subscriber: ${input.subscriberUsername}`);
  draw(`Issue date: ${input.issueDate}`);
  draw(`Status: ${input.status}`);
  draw(`Amount: ${input.amount} ${input.currency}`);
  draw(" ");
  draw("This document was generated by the billing system.", 9);
  return doc.save();
}

export async function buildReceiptPdfBytes(input: {
  paymentId: string;
  invoiceNo: string | null;
  amount: string;
  currency: string;
  paidAt: string;
  method: string;
  subscriberUsername: string;
}): Promise<Uint8Array> {
  const doc = await PDFDocument.create();
  const page = doc.addPage([612, 792]);
  const font = await doc.embedFont(StandardFonts.Helvetica);
  let y = 750;
  const draw = (text: string, size = 11) => {
    page.drawText(text, { x: 50, y, size, font, color: rgb(0.1, 0.1, 0.12) });
    y -= size + 6;
  };
  draw("Future Radius — Payment receipt", 16);
  draw(`Payment ID: ${input.paymentId}`);
  draw(`Subscriber: ${input.subscriberUsername}`);
  if (input.invoiceNo) draw(`Invoice: ${input.invoiceNo}`);
  draw(`Paid at: ${input.paidAt}`);
  draw(`Method: ${input.method}`);
  draw(`Amount: ${input.amount} ${input.currency}`);
  draw(" ", 9);
  draw("Thank you.", 10);
  return doc.save();
}
