-- Dynamic speed profiles, schedules, overrides, and change audit.
-- Idempotent: CREATE IF NOT EXISTS; safe to re-run via applyAllMigrations.

CREATE TABLE IF NOT EXISTS speed_profiles (
  id CHAR(36) NOT NULL PRIMARY KEY,
  tenant_id CHAR(36) NOT NULL,
  branch_id CHAR(36) NULL,
  name VARCHAR(160) NOT NULL,
  download_rate VARCHAR(64) NOT NULL DEFAULT '0',
  upload_rate VARCHAR(64) NOT NULL DEFAULT '0',
  burst_download_rate VARCHAR(64) NULL,
  burst_upload_rate VARCHAR(64) NULL,
  burst_threshold_download VARCHAR(64) NULL,
  burst_threshold_upload VARCHAR(64) NULL,
  burst_time VARCHAR(64) NULL,
  priority INT NOT NULL DEFAULT 8,
  mikrotik_rate_limit_value VARCHAR(255) NOT NULL,
  is_default TINYINT(1) NOT NULL DEFAULT 0,
  is_active TINYINT(1) NOT NULL DEFAULT 1,
  created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  updated_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  KEY idx_speed_profiles_tenant (tenant_id),
  KEY idx_speed_profiles_tenant_active (tenant_id, is_active),
  KEY idx_speed_profiles_tenant_default (tenant_id, is_default, is_active),
  CONSTRAINT fk_speed_profiles_tenant FOREIGN KEY (tenant_id) REFERENCES tenants(id) ON DELETE CASCADE,
  CONSTRAINT fk_speed_profiles_branch FOREIGN KEY (branch_id) REFERENCES branches(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS speed_profile_schedules (
  id CHAR(36) NOT NULL PRIMARY KEY,
  tenant_id CHAR(36) NOT NULL,
  branch_id CHAR(36) NULL,
  name VARCHAR(160) NOT NULL,
  target_type VARCHAR(32) NOT NULL,
  target_id CHAR(36) NULL,
  speed_profile_id CHAR(36) NOT NULL,
  fallback_speed_profile_id CHAR(36) NULL,
  starts_at DATETIME(3) NULL,
  ends_at DATETIME(3) NULL,
  days_of_week JSON NULL,
  time_start TIME NULL,
  time_end TIME NULL,
  timezone VARCHAR(64) NOT NULL DEFAULT 'UTC',
  priority INT NOT NULL DEFAULT 100,
  repeat_mode VARCHAR(24) NOT NULL DEFAULT 'daily',
  condition_type VARCHAR(32) NOT NULL DEFAULT 'always',
  is_active TINYINT(1) NOT NULL DEFAULT 1,
  coa_disconnect_on_rate_fail TINYINT(1) NOT NULL DEFAULT 1,
  notify_subscriber_whatsapp TINYINT(1) NOT NULL DEFAULT 0,
  created_by CHAR(36) NULL,
  created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  updated_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  KEY idx_sps_tenant_active (tenant_id, is_active),
  KEY idx_sps_tenant_target (tenant_id, target_type, target_id),
  CONSTRAINT fk_sps_tenant FOREIGN KEY (tenant_id) REFERENCES tenants(id) ON DELETE CASCADE,
  CONSTRAINT fk_sps_branch FOREIGN KEY (branch_id) REFERENCES branches(id) ON DELETE SET NULL,
  CONSTRAINT fk_sps_profile FOREIGN KEY (speed_profile_id) REFERENCES speed_profiles(id) ON DELETE CASCADE,
  CONSTRAINT fk_sps_fallback FOREIGN KEY (fallback_speed_profile_id) REFERENCES speed_profiles(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS subscriber_speed_overrides (
  id CHAR(36) NOT NULL PRIMARY KEY,
  tenant_id CHAR(36) NOT NULL,
  subscriber_id CHAR(36) NOT NULL,
  speed_profile_id CHAR(36) NOT NULL,
  reason VARCHAR(255) NULL,
  starts_at DATETIME(3) NULL,
  ends_at DATETIME(3) NULL,
  is_active TINYINT(1) NOT NULL DEFAULT 1,
  notify_subscriber_whatsapp TINYINT(1) NOT NULL DEFAULT 0,
  created_by CHAR(36) NULL,
  created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  updated_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  KEY idx_sso_tenant_sub (tenant_id, subscriber_id, is_active),
  KEY idx_sso_ends (tenant_id, ends_at),
  CONSTRAINT fk_sso_tenant FOREIGN KEY (tenant_id) REFERENCES tenants(id) ON DELETE CASCADE,
  CONSTRAINT fk_sso_sub FOREIGN KEY (subscriber_id) REFERENCES subscribers(id) ON DELETE CASCADE,
  CONSTRAINT fk_sso_profile FOREIGN KEY (speed_profile_id) REFERENCES speed_profiles(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS speed_profile_change_logs (
  id CHAR(36) NOT NULL PRIMARY KEY,
  tenant_id CHAR(36) NOT NULL,
  subscriber_id CHAR(36) NOT NULL,
  old_profile_id CHAR(36) NULL,
  new_profile_id CHAR(36) NULL,
  old_mikrotik_value VARCHAR(255) NULL,
  new_mikrotik_value VARCHAR(255) NULL,
  source VARCHAR(32) NOT NULL,
  schedule_id CHAR(36) NULL,
  applied_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  reverted_at DATETIME(3) NULL,
  status VARCHAR(32) NOT NULL DEFAULT 'applied',
  coa_ok TINYINT(1) NULL,
  coa_message VARCHAR(512) NULL,
  error_message VARCHAR(512) NULL,
  KEY idx_spcl_tenant_sub (tenant_id, subscriber_id, applied_at),
  KEY idx_spcl_tenant_time (tenant_id, applied_at),
  CONSTRAINT fk_spcl_tenant FOREIGN KEY (tenant_id) REFERENCES tenants(id) ON DELETE CASCADE,
  CONSTRAINT fk_spcl_sub FOREIGN KEY (subscriber_id) REFERENCES subscribers(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
