CREATE TABLE IF NOT EXISTS backup_rclone_settings (
  tenant_id CHAR(36) NOT NULL PRIMARY KEY,
  enabled TINYINT(1) NOT NULL DEFAULT 0,
  remote_name VARCHAR(64) NULL,
  remote_path VARCHAR(255) NULL,
  config_text LONGTEXT NULL,
  last_check_ok TINYINT(1) NULL,
  last_check_at DATETIME NULL,
  last_error TEXT NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
